### PR TITLE
chore: upgrade aws-cdk to v2.118.0

### PR DESCRIPTION
**Pull request by justindra**
We need to use the recently published Bedrock to Step functions integration in CDK [2.115.0](https://github.com/aws/aws-cdk/releases/tag/v2.115.0) so just updating this to the latest so we can continue to use it.

### CODE REVIEW

**Comment by jayair** [comment]
Pinging the team.

**Comment by justindra** [comment]
@jayair any updates on this?

**Comment by jayair** [comment]
Sorry Justin, we've been a little behind. Pinging again.

**Comment by dylanirion** [comment]
I wouldn't mind a bump to 2.119.0 for [0042e53](https://github.com/aws/aws-cdk/commit/0042e531257eb6979e1e90117316004a643c60a8). Not sure if a separate PR would be necessary here? I've also not tested 2.119.0 so I guess I'm not really bringing much to the table at all here.

**Comment by ashleyfrieze** [comment]
We need a more recent CDK also. I can't work out which is the first one to contain serverless Redis, but 2.121.1 definitely does.

**Comment by fwang** [comment]
Released 2.40.0 with the latest CDK v2.124.0

Thanks @justindra! The update took some work as a few CDK alpha packages graduated to stable packages.

**Comment by justindra** [comment]
Awesome, thanks @fwang!

**Pull request closed without merging**
