### PR TITLE
feat(python-bundling): allow for excluding files and folders from bundle

### LINKED ISSUE #720: Add `exclude` option for Function to exclude certain directories
When creating a [Function](https://docs.serverless-stack.com/constructs/Function#configure-bundling-a-python-function), there is no option to exclude directories from the `srcPath`. This `exclude` should be able to interact with CDK's [`AssetOption.exclude`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html#exclude) directly

One usage of this would be for python sources that have their `.venv` in the same directory as the `Pipfile`.

Without the `exclude` of `.venv`, the `.venv` is bundled together with the lambda, including the packages installed by the dependency builder on the docker, effectively copying the packages twice. This bloats the python runtime lambda code and can lead to failed deployments due to exceeding the [250MB Deployment package size](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)

### PR DESCRIPTION
**Pull request by sladg**
Fixes #720 for Python runtime.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks @sladg!

**Comment by sladg** [comment]
@fwang yeah! that sounds like a reasonable thing, we good with adding `glob` to our dependencies?

**Comment by fwang** [comment]
@sladg Yeeeah! Let's do it!

**Comment by CestDiego** [comment]
;O Thanks for this. Just what I needed. Are there other ways we can exclude compiled cache files?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
