### PR TITLE
feat(NextjsSite): expose revalidation resources for CloudWatch Alarm monitoring

### PR DESCRIPTION
**Pull request by jakevollkommer**
The NextjsSite construct now exposes the following properties for the revalidation resources:

- `revalidationQueue`: The SQS queue used for revalidation events
- `revalidationTable`: The DynamoDB table used for revalidation cache
- `revalidationFunction`: The Lambda function that processes revalidation events

This allows users to add monitoring and observability to these managed resources for SOC2 compliance.

### CODE REVIEW

**Comment by jayair** [comment]
Nice! Can we add some TS Doc comments for those props? So they'll get generated in the docs site.

**Comment by jakevollkommer** [comment]
@jayair added TS Docs, but while doing so figured we could also add the ability for users to pass in their own custom resource configuration, but looks like this may have broken something? should I make this a breaking change in the commit message?

**Comment by jayair** [comment]
Oh I'll have to ask the team to review then.

**Comment by jakevollkommer** [comment]
I only say so because the tests above failed

**Comment by fwang** [comment]
@jakevollkommer the revalidation resources are a bit of work for ppl to create. A pattern we try to do is provider static methods helping ppl to create them, and then they can pass them back in.

In the meanwhile, i like ur initial implementation. I copied what u had and exposed them under `cdk.` - https://github.com/sst/sst/pull/3869

Let me know if it looks good. I can merge that one first.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by jakevollkommer** [comment]
@fwang i adapted this PR for sst v3 in [this PR](https://github.com/sst/sst/pull/5010)

**Pull request closed without merging**
