### PR TITLE
[Construct/SSR]: Add optional viewerProtocolPolicy to SSR Functions

### PR DESCRIPTION
**Pull request by alexabidri**
This PR adds an optional `viewerProtocolPolicy` parameter to the SSR functions. This parameter allows the default value for cloudfront functions deployed with `REDIRECT_TO_HTTPS` to be overridden.

To use this new parameter, simply pass in a string value of either `https-only` or `redirect-to-https`. If no value is provided, the default behavior of `redirect-to-https` will be used.

This change should make it easier to customize the behavior of the SSR functions for different deployment scenarios.

_Note: Also added for StaticSite and Service construct_

### CODE REVIEW

**Comment by alexabidri** [comment]
@fwang Could you please have a check on this PR? Thanks a lot 🙏🏻

**Review by bayssmekanique — COMMENTED** [review]
Alternative which avoids adding a top level `prop` is to use the attribute already defined on `cdk.distribution.defaultBehavior.viewerProtocolPolicy`.

```ts
viewerProtocolPolicy: cdk?.distribution?.defaultBehavior?.viewerProtocolPolicy ?? ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
```

**Comment by alexabidri** [comment]
@bayssmekanique Thanks for reviewing! I have updated the PR according to your feedback 👍🏻

**Review by bayssmekanique — COMMENTED** [review]
Looks great to me!

**Pull request closed without merging**
