### PR TITLE
Update AWS CDK and SDK Versions

### PR DESCRIPTION
**Pull request by san4d**
# Summary
Update AWS SDK dependencies to 3.454.0 and AWS CDK dependencies to 2.110.1.

# Notes
- Deprecated versions were not changed.
- Other dependencies were not changed.
- Changes verified against my project.

### CODE REVIEW

**Comment by san4d** [comment]
This may duplicate https://github.com/sst/sst/pull/3517. I'm leaving this open for now in the event that the smaller scope helps get it through.

**Comment by jayair** [comment]
Hmm so the CDK update. But we'll need a separate PR for the Astro update. Wanna put that together?

**Comment by san4d** [comment]
Sure thing! I'll split out the SDK and CDK updates from the Astro updates.

**Comment by san4d** [comment]
Astro changes are here:
https://github.com/sst/sst/pull/3523

It is not as pressing as updating the AWS versions.

**Comment by fwang** [comment]
Thanks @san4d! Will be in the next release.

**Pull request merged**
