### PR TITLE
Fix: Update nodejs 14 -> 16 for custom resource support functions

### PR DESCRIPTION
**Pull request by jamesgibbons92**
In the past few days AWS have scheduled EOL for Lambda NodeJS 14 and sent out the following message to anyone using that version:

```
We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using the Node.js 14 runtime.
We are ending support for Node.js 14 in AWS Lambda. This follows Node.js 14 End-Of-Life (EOL) reached on April 30, 2023 [1].
```

CDK have updated most of their CR now to use at least node16. So the next CDK bump should pull in those updates automatically, there are a couple of SST custom resources that use node14 however so this PR just bumps them to 16.

I considered node18 but would require a re-write of dns validator function as it doesn't bundle the aws-sdk deps, and node18 lambda does not include aws-sdk v2 in the runtime

### CODE REVIEW

**Comment by fwang** [comment]
Thanks @jamesgibbons92 @bobbypiper

**Comment by bobbypiper** [comment]
@jamesgibbons92 @fwang 

https://nodejs.org/en/blog/announcements/nodejs16-eol

LOL!

**Comment by jayair** [comment]
lol

**Comment by ssrowe** [comment]
Are there any plans to update SST to use nodejs18.x for customer resources and handlers?

**Comment by This-Is-Not-Brad** [comment]
Yes, AWS is pinging us about Node 16 EOL, for the Custom Resource Handler and Certificate Request Functions

**Comment by DianomiJH** [comment]
I've been getting Pinged for the CustomS3AutoDeleteObjectsCustomResourceHandler

**Comment by jayair** [comment]
Are these related to the SST Bootstrap stack btw?

**Comment by DianomiJH** [comment]
Yes the Auto Delete Objects one i reported is SST Bootstrap

**Pull request merged**
