### PR TITLE
Fix/removal policy docs

### PR DESCRIPTION
**Pull request by ridzchandra**
[Here]

(https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.core/RemovalPolicy.html#aws_cdk.core.RemovalPolicy.DESTROY:~:text=%5D%22%22%22)%0A)-,Attributes,-DESTROY) is the source docs page from "aws-cdk" 🙂

I also tested to check if it's correct, on my local lambda dev before making the corrections. ✌🏻

### CODE REVIEW

**Comment by jayair** [comment]
Hmm I might be a little confused. Do you mind sharing why you wanted to make this change?

**Comment by ridzchandra** [comment]
> https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.core/RemovalPolicy.html#aws_cdk.core.RemovalPolicy.DESTROY:~:text=%5D%22%22%22)%0A)-,Attributes,-DESTROY

@jayair , SST docs are showing that the default policy is RETAIN and we need to manually set it to DESTROY when needed. However, As it shows in the aws-cdk-lib docs, DESTROY is the default, and we need to manually set it to RETAIN when needed.

**Comment by fwang** [comment]
Just chiming in, there actually isn't a default removal policy. It's RETAIN for stateful resources, and DESTROY for non-stateful resources. It's briefly mentioned in the doc @ridzchandra shared above:
> Many stateful resources in the AWS Construct Library will accept a removalPolicy as a property, typically defaulting it to RETAIN.

This can be think of as SST/CDK will retain your data upon removal (ie. S3 bucket, logs, etc). And if you want a clean remove, you'd have to set the removal policy to `DESTROY`.

Let me know if that makes sense.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
