### PR TITLE
Dynamic RevalidationInsertFunction provisioning based on prerender-manifest size

### PR DESCRIPTION
**Pull request by dkershner6**
With enough prerendered pages, 128MB is not enough memory.

### CODE REVIEW

**Review by khuezy — APPROVED** [review]
LGTM

**Comment by jayair** [comment]
https://discord.com/channels/983865673656705025/1165305280943358012/1167608904595816508

**Comment by dkershner6** [comment]
This is good to go at any time, I have no further testing or changes to make.

**Comment by dkershner6** [comment]
Not sure why this one closed, something in my fork caused it.

**Comment by dkershner6** [comment]
Thank you.

**Pull request merged**
