### PR TITLE
Docs: Added NextJS + RDS + Drizzle + migrations script example

### PR DESCRIPTION
**Pull request by jonbnewman**
My particular stack choice (NextJS + RDS + Drizzle, including migrations) didn't have an example...nor was there really an example that was close.

So after [asking on the discord](https://discord.com/channels/983865673656705025/1084270849206526163/1205574495533015090) and tinkering around with my own application I came up with a solution that seemed reasonable. I felt it might be good to share the core of what I had done in an example, and so I made one.

It includes the following:

* SST application setup in standalone mode
* [NextJS](https://nextjs.org) web package (using `TS` + `Tailwind` + `App` router)
* [SST RDS](https://docs.sst.dev/constructs/RDS) (PostgreSQL database)
* [SST Script](https://docs.sst.dev/constructs/Script) (run drizzle migrations created in the NextJS site on deploy)
* [Drizzle ORM](https://orm.drizzle.team/)

All dependencies are latest as of this PR being issued. I made sure to standup the example application after creating it and verified everything works.

Please let me know if you guys would like anything changed, or if you don't care for this at all feel free to close it.

### CODE REVIEW

**Comment by jayair** [comment]
Oh nice this is super useful. We would love to add this.

There's only one little issue. Our examples are generated from these presets. It helps keep the versions up to date. Here's an example https://github.com/sst/sst/tree/master/packages/create-sst/bin/presets/examples/quickstart-nextjs

This specifies what's in the package.json https://github.com/sst/sst/blob/master/packages/create-sst/bin/presets/examples/quickstart-nextjs/preset.mjs#L9 and you can move all your project files inside the `templates/`, for ex: https://github.com/sst/sst/tree/master/packages/create-sst/bin/presets/examples/quickstart-nextjs/templates

Let me know if that makes sense. If not then I can take a crack at it.

**Comment by jonbnewman** [comment]
@jayair well...I *think* I did what was correct, although admittedly I am unsure of how to test this off hand (if you could provide a pointer on that I will test using the template locally).

As for what I did, the quick-start template was too simplistic to directly copy/edit from. The template I created needed a `function` created as well as a `NextJS` site. After looking into the `create-sst` code and some of the other templates a bit, I *think* I came up with a template I think would work...although I am flying a bit blind here without some wanted context.

Anyways, please take a look and let me know what you think.

**Comment by jayair** [comment]
Appreciate it! I'll take a look.

**Comment by jayair** [comment]
Let me try and generate them and I'll report back.

**Comment by jayair** [comment]
Here it is: https://github.com/sst/sst/tree/master/examples/nextjs-rds-drizzle

Let me know if it turned out okay.

**Pull request merged**
