### PR TITLE
[Bucket] Update bucket notification type queue missing

### PR DESCRIPTION
**Pull request by tranlehaiquan**
It seems type is required when pass a notification with queue
image

### CODE REVIEW

**Comment by jayair** [comment]
Is this for SST v1?

**Comment by tranlehaiquan** [comment]
Hi @jayair 
I'm running 2.13.2
image

**Comment by jayair** [comment]
It's just that the files changed in this PR are for v0 and v1. Was that intentional?

**Comment by tranlehaiquan** [comment]
Hi @jayair 
Sorry, I update the wrong page. I push the new commit and revert document v1 and v0.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
