### PR TITLE
Allow for additional S3 Origin props, mostly for security reasons

### LINKED ISSUE #3469: (SSRSite, NextjsSite, etc) Not possible to use shared S3 bucket without giving public access
The OAI created doesn't actually get into the bucket policy, presumably because it is in another stack.

### PR DESCRIPTION
**Pull request by dkershner6**
Resolves #3469 

Needed for Rollback capability without compromising security: https://discord.com/channels/983865673656705025/1167264627709722635

Sorry for the additional commits, will clean up as soon as https://github.com/sst/sst/pull/3436 is merged.  Anything I try to do to solve it closes the other PR.  I normally use branches, but the prior PR is blocking our ability to deploy.

### CODE REVIEW

**Comment by jayair** [comment]
Did you want to update this guy now that the other one has been merged? Or is it good to be reviewed?

**Comment by dkershner6** [comment]
Good to go.  The diff is correct even if the commit history is off.

**Comment by dkershner6** [comment]
Sorry about the V1, ill pay more attention.

**Comment by fwang** [comment]
Oh not at all! The updated examples in docs really helps.

**Pull request merged**
