### PR TITLE
Feature/add optional access_type prop to oauth adapter

### PR DESCRIPTION
**Pull request by jamsmd**
Hi guys,

In order to receive a refreshtoken from google using OAuth2 you're required to add the `access_type` queryparam to the google oauth redirect url.

This PR is doing just that.

I've set the `access_type` type to the exact values: `'online' | 'offline'` I can also change it to just a `string` if that's preferred.

Kind regards

### CODE REVIEW

**Comment by fwang** [comment]
Hey @jamsmd, do u have a link to where the `access_type` is mentioned, I just want to take a quick look before merging this :)

**Comment by jamsmd** [comment]
Hey @fwang ,

Yes of course!

You can find it here:
https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters

under `Authentication URI parameters` it says:
```
The following table gives more complete descriptions of the parameters accepted by Google's OAuth 2.0 authentication API.

Parameter: access_type
Required: (Optional)
Description : The allowed values are offline and online. The effect is documented in Offline Access; if an access token is being requested, the client does not receive a refresh token unless a value of offline is specified.
```


And also here:
https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient

Under `Step 1: Set authorization parameters` in the code snippet is says this:
```
// Generate a url that asks permissions for the Drive activity scope
const authorizationUrl = oauth2Client.generateAuthUrl({
  // 'online' (default) or 'offline' (gets refresh_token)
  access_type: 'offline',
  /** Pass in the scopes array defined above.
    * Alternatively, if only one scope is needed, you can pass a scope URL as a string */
  scope: scopes,
  // Enable incremental authorization. Recommended as a best practice.
  include_granted_scopes: true
});
```

**Comment by jamsmd** [comment]
Hey @fwang,

Did you find any time to check the docs I sent?

**Review by 53jk1 — APPROVED** [review]

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
