### PR TITLE
[Construct/NextjsSite] Allow page router preview mode to bypass the cloudfront cache

### PR DESCRIPTION
**Pull request by JanStevens**
Hi,

In Next.js page router when using preview mode we often received the cached page instead of the preview version. This ensures that when we are in preview mode (depends on the cookie `__prerender_bypass`) we set a header called `x-prerender-bypass` which is added to the list in `DEFAULT_CACHE_POLICY_ALLOWED_HEADERS`.

Thanks @conico974 for the help

Relevant discord discussion: https://discord.com/channels/983865673656705025/1179733950533480538

### CODE REVIEW

**Comment by jayair** [comment]
Thanks!

**Comment by JanStevens** [comment]
@jayair Just wondering whats preventing currently for getting this merged and how I can assist in getting it to a point where its acceptable? I've seen a couple of discord questions specifically mentioning that pages router + preview is broken in open next and this fixes it.

**Comment by jayair** [comment]
Oh no the team might've missed this. I'll ping them.

**Comment by fwang** [comment]
Thanks @JanStevens! Will be in the next release.

**Pull request merged**
