### PR TITLE
feat: allow customization of IAM permissions on resource binding

### LINKED ISSUE #2210: Resource binding: allow customizing IAM permissions
Akos suggested:
> maybe like how permissions are done, i.e. you can pass one of the CDK methods of 'grantReadWrite' or 'grantRead'?

---
Requests:
- Akos https://discord.com/channels/983865673656705025/983866416832864350/1042492439295971348

### LINKED ISSUE #2247: Use reduced permissions with `bind`-ed constructs
I read the documentation on [resource binding](https://docs.sst.dev/resource-binding) and would love to use it, but it grants full permissions on the bound resource. I prefer to ratchet my permissions as tight as they can go, especially for handlers that don't need write access to resources. Is there a way to specify the permissions when `bind`ing a construct? If there's not, could it be added, perhaps in a similar way to how `attachPermissions` works - e.g. `api.bind([[bucket, "s3:GetObject"]])`?

#2186 mentions `bind` granting all permissions on a resource, and uses `attachPermissions` as a workaround. This grants fewer permissions but does not gain all the benefits of `bind`, such as type safe access to construct properties in lambdas.

### PR DESCRIPTION
**Pull request by justindra**
Resolves #2210, resolves #2247 

Allows overriding of the default permissions provided by binding options, so we can restrict permissions better.

```ts
site.bind([[bucket, { permissions: ["s3:GetObject", "s3:ListObjects"] }]]);
```

The IAM policy statement would then look like:

```yml
{
  "Action": "s3:GetObject",
  "Resource": ["arn:aws:s3:::{BUCKET_NAME}", "arn:aws:s3:::{BUCKET_NAME}/*"],
  "Effect": "Allow",
},
{
  "Action": "s3:ListObjects",
  "Resource": ["arn:aws:s3:::{BUCKET_NAME}", "arn:aws:s3:::{BUCKET_NAME}/*"],
  "Effect": "Allow",
}
```

### CODE REVIEW

**Comment by justindra** [comment]
@jayair @fwang just checking in to see if there's been any more discussion on this internally and if there's anything I can do to get this merged in?

**Comment by jayair** [comment]
I think Frank is working through the PRs, he should get to this soon. If he doesn't mention me again?

**Comment by justindra** [comment]
@jayair just pinging you on any updates for this PR.

**Comment by jayair** [comment]
Oh I'll check. Maybe he missed this, cos we went through most of them.

**Comment by justindra** [comment]
@jayair just pinging on progress

**Comment by fwang** [comment]
Thanks @justindra. There are a few other places needed to change. I took ur idea and implemented in #3687 

You can do:
```ts
site.bind([
  { resource: bucket, permissions: [{ actions: ["s3:GetObject"], resources: [`${bucket.arn}/*`] }] }
]);
```

**Pull request closed without merging**
