### PR TITLE
Update Astro Version to 3.6.0

### PR DESCRIPTION
**Pull request by san4d**
# Summary
Updates the Astro dev dependency to 3.6.0 in `astro-sst`.

### CODE REVIEW

**Comment by jayair** [comment]
@bayssmekanique does this look okay?

**Comment by bayssmekanique** [comment]
I just tested the branch and it builds and deploys fine. I'm not entirely certain the reason for updating the version since it's a dev dependency but the PR looks good.

**Comment by jayair** [comment]
@san4d wanna share the reason for the update?

**Comment by san4d** [comment]
I was updating the AWS versions and thought I'd bump this too. I have no compelling reason. I'll close this out.

**Pull request closed without merging**
