### PR TITLE
chore: update aws-cdk-lib to 2.141.0 from 2.132.1

### PR DESCRIPTION
**Pull request by berenddeboer**
Bump aws-cdk-lib version.

### CODE REVIEW

**Comment by krmorse** [comment]
+1 thank you!  looking forward to this getting released, as we're stuck on a pretty old version of `sst` due to the `cdk diff` bug in `2.132.1`

**Comment by berenddeboer** [comment]
@krmorse we need this because it makes it easier to set resolver and depth limits on the graphql api instead of resorting to the escape hatch.

**Comment by berenddeboer** [comment]
And fixed the commit, as I had switched to lockfile version 9 here, kept it at 6 now.

**Comment by fwang** [comment]
Thanks @berenddeboer!

**Pull request merged**
