### PR TITLE
feat: Adds layers prop to SSR Functions

### PR DESCRIPTION
**Pull request by bayssmekanique**
Not added for Next sites as necessary Node prop is also absent.

### CODE REVIEW

**Comment by graimondo** [comment]
Very useful PR, follow to see when added to codebase

**Comment by fwang** [comment]
Thanks @bayssmekanique, made a quick update.

Moved `layers` into `cdk.layers`. The thinking was that any prop that takes an CDK object goes into `cdk.*`. And if that prop becomes commonly used, SST will figure out a way for ppl to pass that in without needing to import CDK.

Can u give it a quick test?

**Comment by bayssmekanique** [comment]
@fwang, it appears there are permissions missing for the IAM role to get a `LayerVersion` from an ARN.

```ts
        cdk: {
          server: {
            layers: [lambda.LayerVersion.fromLayerVersionArn(stack, 'ChromeLayer', layerArn)]
          }
        }
```

```shell
|  Site astro-site/ServerFunction/ServerFunction/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
|  Site astro-site/ServerFunction/ServerFunction AWS::Lambda::Function CREATE_FAILED Resource handler returned message: "User: arn:aws:sts::856863919685:assumed-role/cdk-hnb659fds-cfn-exec-role-856863919685-us-west-2/AWSCloudFormation is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:22 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: 304ccc37-ed2e-4418-86fd-158451888f08)" (RequestToken: e6fa1c44-68cf-b507-9c25-bc93fc9b7e2a, HandlerErrorCode: AccessDenied)
|  Site astro-site/Certificate/CertificateRequestorResource AWS::CloudFormation::CustomResource CREATE_FAILED Resource creation cancelled                                                                                           
|  Site astro-site/S3Handler/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_FAILED Resource creation cancelled
```

**Comment by fwang** [comment]
Lambda is deployed to `us-west-2` and the layer is in `us-east-1`. Could that be the issue? Also, does that layer allow cross account usage?

^ I havne't used layers much.. I might not know what I'm talking about

**Comment by bayssmekanique** [comment]
Good call @fwang, that was the issue. This appears to work as expected using the CDK configuration.

image

**Comment by adamelmore** [comment]
@fwang anything else needed on this?

**Comment by bayssmekanique** [comment]
Going to create a new PR that's for SSR, not just Astro.

**Pull request closed without merging**
