### PR TITLE
fix: update image optimizer cache policy

### PR DESCRIPTION
**Pull request by gkaskonas**

### CODE REVIEW

**Review by khuezy — APPROVED** [review]
LGTM. Do we want to allow the user to specify any of the cache policy props for customizations? I don't see a need, but someone might have a use case for it.

**Comment by gkaskonas** [comment]
I added this policy manually to my project and lambda is now failing with

`Cannot destructure property 'url' of 'a' as it is undefined.`

**Comment by khuezy** [comment]
@gkaskonas can you add `"accept"` to your header cache. I think that might be required.

**Review by khuezy — CHANGES_REQUESTED** [review]
I believe we need to add "accept" to the header cache.

**Comment by gkaskonas** [comment]
I don't think you need the accept header in the cache

**Comment by khuezy** [comment]
ok, everything works now?

**Comment by gkaskonas** [comment]
Yeah everything is working with `Query strings - All` cache key settings. I am getting better hit ratio on the images

**Comment by conico974** [comment]
You do need to add the accept headers, otherwise it might send the wrong format to the end user https://github.com/vercel/next.js/blob/ffafad2c35a3f9677bb520f68e989f58f192b931/packages/next/src/server/image-optimizer.ts#L712

**Comment by Tutai89** [comment]
Thanks

**Comment by gkaskonas** [comment]
Added accept header

**Comment by khuezy** [comment]
Thanks @gkaskonas one more thing please: can you add comments w/ a little explanation and the link to the Nextjs repo that Conico linked? That'll help other devs understand the context more in the future.

**Comment by khuezy** [comment]
Just FYI, w/o the `accept` header, the image optimization won't optimize to `webp`

**Comment by gkaskonas** [comment]
Added the comment

**Review by khuezy — APPROVED** [review]

**Comment by gkaskonas** [comment]
Does accept need to be uppercase?

**Comment by khuezy** [comment]
I don't think so, the old policy has lower case everything and it works. But if you want to be 100% sure, then change it to "Accept"

**Comment by gkaskonas** [comment]
If it works it works. Who can merge this?

**Comment by jayair** [comment]
Can we fix the conflicts and I'll ask the team to review? Unfortunately, we did a big refactor of the SSR Sites to make it easier to take contributions. So the merge might not be super simple.

**Comment by gkaskonas** [comment]
Not sure if thats the cleanest way to set u p a different policy for image optimization. I am open to suggestions

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
