### PR TITLE
ECS (Service): allow disabling default autoscaling

### PR DESCRIPTION
**Pull request by zxan1285**
Hi!
There's a tiny change i need to setup my ECS autoscaling. I need to scale it based on SQS metric, and i also don't want to scale based on default params (cpu, memory).
With this tiny change i can disable default autoscaling by explicitly set scaling to null (`scaling: null`) and then use 
`service.cdk.fargateService.autoScaleTaskCount()` to create any custom scaling scenarios i want. 
Thanks!

### CODE REVIEW

**Comment by jayair** [comment]
Can you open an issue for this? I'll assign it to the team and have it looked at.

We might want to decide if we want it to be `null`.

**Comment by zxan1285** [comment]
> Can you open an issue for this? I'll assign it to the team and have it looked at.
> 
> We might want to decide if we want it to be `null`.

Thank you!
#3843 created

I do not insist on `null`, i'm just too lazy to add types for ts to accept anything else :)

**Comment by zxan1285** [comment]
@jayair i've been thinking on alternatives for that `null`. I guess, it could be something like `scaling: { disabled: true }` or `scaling: { enabled: false }`. Though i'm not sure it is better than just `null`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Pull request closed without merging**
