### PR TITLE
Revert switch to node18 for DNS-validated certificate requestor func

### PR DESCRIPTION
**Pull request by jaydeebee**
This PR reverts the node18 upgrade on dns-validated-certificates' `requestorFunction` included in [a broader upgrade to node18 for all functions](https://github.com/sst/sst/commit/cbd4510b1f16a141a85597bfbd1ff958f5026edd), released in 2.36.2.  It appears that the node18 runtime doesn't have `aws-sdk` in it, so this drops back to node16 for that one function.  (there may be other functions affected in the node18 change, this is the only one that happened to affect me)

### CODE REVIEW

**Comment by bayssmekanique** [comment]
My understanding from the AWS documentation is that it's still installed, but it has changed SDK from `v2` to `v3`. What was the specific error that was occurring?

**Comment by jaydeebee** [comment]
I was seeing:
```
2023-11-21T22:05:52.614Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

**Comment by jaydeebee** [comment]
aws-sdk v2 is a bit different from v3, that's when they did [the modular breakout](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/), right?  i meant there's no `aws-sdk` specifically, but probably would be `@aws-sdk/client-s3` on node 18 containers.

**Comment by jayair** [comment]
Hmm taking a look

**Comment by fwang** [comment]
@jaydeebee I bundled `aws-sdk` into the `dns-validated-certificate`. Can you try out this canary release `sst@0.0.0-20231123182010` and let me know if it works for you?

**Comment by jaydeebee** [comment]
> @jaydeebee I bundled `aws-sdk` into the `dns-validated-certificate`. Can you try out this canary release `sst@0.0.0-20231123182010` and let me know if it works for you?

hmm, not quite yet, logs for the function are catching:
```
2023-11-23T18:51:17.997Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.certificateRequestHandler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.certificateRequestHandler is undefined or not exported",
        "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```
lemme know when the next one's ready, i'll be around.

**Comment by fwang** [comment]
Thanks @jaydeebee! Fixed, and tested it works.

Will be in the next release.

**Pull request merged**
