### PR TITLE
Fix: Prevent overriding environment variables with values from .env

### PR DESCRIPTION
**Pull request by slyapustin**
Fixed https://github.com/serverless-stack/sst/issues/2523

### CODE REVIEW

**Comment by thdxr** [comment]
thanks for the PR! i think the default is false so you could just remove the config object entirely

**Review by slyapustin — COMMENTED** [review]
-

**Comment by jayair** [comment]
@slyapustin any idea why this got closed?

**Comment by ackinc** [comment]
@jayair Sergey seems to have deleted his fork of sst, so I don't think this PR's coming back. I created a new one doing the same thing here: https://github.com/sst/sst/pull/3305

**Pull request closed without merging**
