### PR TITLE
sst/NextjsSite: add option to specify custom build output path

### PR DESCRIPTION
**Pull request by morficus**
- updating `NextjsSiteProps` with the new option called `buildOutputPath`
- updating the constructor to pass this value to OpenNext optionally

See issue #3515 for more details about why I belive this is beneficial.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks, we'll take a look!

**Comment by morficus** [comment]
hey @jayair , have you had a chance to look at this? any feedback?

**Comment by jayair** [comment]
Hmm I missed this somehow. Checking on it with the team.

**Comment by morficus** [comment]
@jayair sorry to ping you again, just wondering if there is any feedback on this PR or if the team decided that there is no need to expose more options from OpenNext?

**Comment by jayair** [comment]
Oops sorry, been a bit busy with the holidays. I'll check again.

**Comment by mstfash** [comment]
Hi, is this implemented yet ?

**Comment by jayair** [comment]
Oh I missed this. I'll ping the team.

**Comment by jayair** [comment]
Might've slipped on this one. Let me ping the team again.

**Comment by fwang** [comment]
Thanks @morficus! Moved the prop to:
```ts
new NextjsSite(stack, "Web", {
  openNext: {
    buildOutputPath: "...",
  }
}
```

Will be in the next release.

**Pull request merged**
