### PR TITLE
Update Service construct to be able to create an http -> https listener on the load balancer itself.

### PR DESCRIPTION
**Pull request by BradyRyun**
Internally, my team needs to be able to create a load balancer with HTTP redirecting traffic to HTTPS. This is an initial start. There needs to be additional configuration available here, but this unblocks myself and should allow others to be able to do the same with a basic setup.

I am open to feedback on how to pass the variables to the construct. I put them at the top-level, but I considered adding them to the applicationLoadBalancer object in the cdk options.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks! Yeah maybe a cdk prop would make more sense. Let me check with the team.

**Comment by BradyRyun** [comment]
@fwang Updated now. JetBrains user so it didn't find the VSCode formatting options preconfigured. Looks good now. :)

**Comment by BradyRyun** [comment]
@fwang @jayair bump. :)

**Comment by jayair** [comment]
I'll ping Frank

**Comment by fwang** [comment]
@BradyRyun sorry about the delay.

I'm hesitate on adding the http to https redirect as a built-in feature. Let's wait and see if more people need it, and we can support it as a top level feature. ie.

That said, I just published `2.41.2` to support customizing the listener. This should make adding http to https redirect easily. Here's an example — https://docs.sst.dev/constructs/Service#configuring-application-load-balancer-http-to-https-redirect

Let me know if that works for you.

**Comment by BradyRyun** [comment]
@fwang This looks like it will work for us. I will let you know once I get a chance to get back to this.

**Pull request closed without merging**
