### PR TITLE
construct/rds - allow postgresql engines 14.10, 15.4 and 16.1

### PR DESCRIPTION
**Pull request by gtdudu**

### CODE REVIEW

**Comment by BartInTheField** [comment]
This would be really useful, we are now relying on patch-package to patch this in our local node_modules.

**Comment by omikader** [comment]
@BartInTheField @gtdudu How do you use this? Are you using serverless RDS v2 with SST?

I tried creating a new SST `RDS` cluster with `postgresql16.1` and am seeing these errors:

```
RdsStack db2/Cluster AWS::RDS::DBCluster CREATE_FAILED Resource handler returned message: "The engine mode serverless you requested is currently unavailable. (Service: Rds, Status Code: 400, Request ID: 407aebbd-922b-460e-aaf8-57c5a44f4cfa)" (RequestToken: 7d93291b-726f-015b-13e9-57bd0d0b2fea, HandlerErrorCode: InvalidRequest)
```

I then ran this command which suggests that the only supported version for Aurora Postgres on serverless v1 is 13.12

```
~ % aws rds describe-db-engine-versions --engine aurora-postgresql --filters Name=engine-mode,Values=serverless --output text --query "DBEngineVersions[].EngineVersion"
13.12
```

**Comment by romulovalez** [comment]
> @BartInTheField @gtdudu How do you use this? Are you using serverless RDS v2 with SST?
> 
> I tried creating a new SST `RDS` cluster with `postgresql16.1` and am seeing these errors:
> 
> ```
> RdsStack db2/Cluster AWS::RDS::DBCluster CREATE_FAILED Resource handler returned message: "The engine mode serverless you requested is currently unavailable. (Service: Rds, Status Code: 400, Request ID: 407aebbd-922b-460e-aaf8-57c5a44f4cfa)" (RequestToken: 7d93291b-726f-015b-13e9-57bd0d0b2fea, HandlerErrorCode: InvalidRequest)
> ```
> 
> I then ran this command which suggests that the only supported version for Aurora Postgres on serverless v1 is 13.12
> 
> ```
> ~ % aws rds describe-db-engine-versions --engine aurora-postgresql --filters Name=engine-mode,Values=serverless --output text --query "DBEngineVersions[].EngineVersion"
> 13.12
> ```

The same happens to me

**Comment by jayair** [comment]
Which SST version are you using?

**Comment by omikader** [comment]
@jayair

```
% pnpm sst version
SST: v2.41.5
CDK: v2.132.1
Constructs: v10.3.0
```

**Pull request merged**
